import {
  filterHealthyFoods,
  getHealthyFood,
  healthyFoodAIIndex,
  type HealthyCategory,
  type HealthyFood,
  type Moment,
} from '@/data/healthyFoods';
import { isDemoMode, supabase } from '@/lib/supabase';
import { buildHealthContext } from '@/services/ai';
import { buildAIDayJournal } from '@/services/dayLog';
import { asQuotaError } from '@/services/usage';
import { useAppStore } from '@/store/useAppStore';
import type { Profile } from '@/types';

/* ────────────────────────────────────────────────────────────
 * HEALTHY MEAL COACH — the "Makla saine" guided assistant.
 *
 * A conversational flow that gathers what the patient wants (which meal,
 * which ingredients, dislikes/allergies), shows a RECAP the patient can
 * confirm or edit, and on "Générer" proposes several dishes: ready ones
 * from our curated catalog PLUS a fully CUSTOM dish built to order (same
 * grams the patient asked for) when nothing in the list matches exactly.
 *
 * Custom dishes are generated by the `ai-chat` edge function (mode
 * `healthy_coach`) and rendered on the SAME detail screen as catalog
 * dishes — we shape them into a `HealthyFood` and keep them in an
 * in-session registry so `/healthy-food?custom=<id>` can resolve them.
 * ──────────────────────────────────────────────────────────── */

/** The confirmation the patient reviews before dishes are generated. */
export interface Recap {
  /** Short human title, e.g. "Déjeuner — salade fraîche". */
  title: string;
  /** Meal-time folder the request is about. */
  meal: Moment | 'any';
  /** One-line human recap of what the patient asked for. */
  summary: string;
  /** Ingredients / attributes they want. */
  wants: string[];
  /** Dislikes / allergies to avoid. */
  avoid: string[];
}

/** A dish the AI invents on the spot from the patient's request. Already
 *  localized in the patient's language (generation is per-language). */
export interface GeneratedDish {
  name: string;
  emoji: string;
  category: HealthyCategory;
  /** Human serving label, e.g. "1 assiette (250 g)". */
  serving: string;
  grams: number;
  calories: number;
  carbs: number;
  sugar: number;
  protein: number;
  fat: number;
  fiber: number;
  gi: number;
  why: string;
  ingredients: string[];
  steps: string[];
}

/** A tappable dish card in the chat — a ready catalog dish, or a custom one. */
export type DishCard =
  | { kind: 'catalog'; id: string; note?: string }
  | { kind: 'custom'; id: string; note?: string; dish: GeneratedDish };

export interface CoachResult {
  reply: string;
  /** Ready-to-tap follow-up chips (e.g. meal choices). */
  quickReplies: string[];
  /** Set once the AI knows enough → the app shows the confirm card. */
  recap: Recap | null;
  /** Set on "Générer" → the app shows the dish cards. */
  dishes: DishCard[] | null;
  /** Faithful transcript when the turn was a voice message. */
  transcript: string;
}

/* ── In-session registry of generated dishes ──
 * Kept in a module Map (not the persisted store): generated dishes are
 * ephemeral, and this survives in-session navigation to the detail page.
 * A stale id (after a full web reload) simply redirects home. */
const customRegistry = new Map<string, HealthyFood>();
let customSeq = 0;

const VALID_CATEGORIES: HealthyCategory[] = [
  'breakfast', 'salad', 'soup', 'main', 'seafood', 'snack', 'drink', 'dessert',
];

const CATEGORY_EMOJI: Record<HealthyCategory, string> = {
  breakfast: '🌅', salad: '🥗', soup: '🍲', main: '🍽️',
  seafood: '🐟', snack: '🥜', drink: '🍵', dessert: '🍓',
};

/** Which meal-time folders a custom dish belongs to (for the detail hero). */
function momentsForCategory(cat: HealthyCategory): Moment[] {
  switch (cat) {
    case 'breakfast': return ['ftour'];
    case 'snack': return ['snack'];
    case 'drink': return ['drink'];
    case 'dessert': return ['dessert'];
    default: return ['ghda', '3cha'];
  }
}

/**
 * Turn a generated dish into a `HealthyFood` so the existing detail screen
 * and its helpers (`healthyFoodName/Why/Ingredients/Steps`) render it with
 * zero changes. The already-localized text goes into every language field.
 */
export function buildCustomHealthyFood(d: GeneratedDish, id: string): HealthyFood {
  const category: HealthyCategory = VALID_CATEGORIES.includes(d.category)
    ? d.category
    : 'main';
  const emoji = d.emoji || CATEGORY_EMOJI[category];
  const grams = Number(d.grams) > 0 ? Math.round(Number(d.grams)) : 0;
  const num = (v: unknown) => (Number.isFinite(Number(v)) ? Math.round(Number(v)) : 0);
  return {
    id,
    name_fr: d.name, name_ar: d.name, name_en: d.name,
    category,
    moments: momentsForCategory(category),
    emoji,
    serving: d.serving || (grams ? `${grams} g` : ''),
    grams,
    calories: num(d.calories),
    carbs: num(d.carbs),
    sugar: num(d.sugar),
    protein: num(d.protein),
    fat: num(d.fat),
    fiber: num(d.fiber),
    gi: num(d.gi),
    why_fr: d.why, why_ar: d.why,
    ingredients_fr: Array.isArray(d.ingredients) ? d.ingredients : [],
    ingredients_ar: Array.isArray(d.ingredients) ? d.ingredients : [],
    steps_fr: Array.isArray(d.steps) ? d.steps : [],
    steps_ar: Array.isArray(d.steps) ? d.steps : [],
  };
}

/** Register a generated dish for in-session lookup; returns its id. */
export function registerCustomDish(food: HealthyFood): string {
  const id = food.id || `custom-${Date.now().toString(36)}-${(customSeq++).toString(36)}`;
  customRegistry.set(id, { ...food, id });
  return id;
}

/** Resolve a generated dish by id (used by the detail screen). */
export function getCustomDish(id: string): HealthyFood | null {
  return customRegistry.get(id) ?? null;
}

/* ── Response parsing helpers ── */
const str = (v: unknown): string => (typeof v === 'string' ? v : '');
const strArr = (v: unknown): string[] =>
  Array.isArray(v) ? v.filter((x): x is string => typeof x === 'string' && !!x.trim()) : [];

function parseRecap(v: unknown): Recap | null {
  if (!v || typeof v !== 'object') return null;
  const o = v as Record<string, unknown>;
  const summary = str(o.summary);
  if (!summary) return null;
  return {
    title: str(o.title) || summary,
    meal: (['ftour', 'ghda', '3cha', 'snack', 'drink', 'dessert'] as const).includes(
      o.meal as Moment
    )
      ? (o.meal as Moment)
      : 'any',
    summary,
    wants: strArr(o.wants),
    avoid: strArr(o.avoid),
  };
}

function parseDishes(v: unknown, meal?: Moment | 'any' | null): DishCard[] | null {
  if (!Array.isArray(v)) return null;
  const out: DishCard[] = [];
  for (const raw of v) {
    if (!raw || typeof raw !== 'object') continue;
    const o = raw as Record<string, unknown>;
    const note = str(o.note);
    const dish = o.dish as Partial<GeneratedDish> | undefined;
    // Custom dish (has a full spec) → register + shape into a HealthyFood.
    if (o.kind === 'custom' || (dish && typeof dish === 'object' && dish.name)) {
      if (!dish || !dish.name || !(Number(dish.grams) > 0)) continue;
      const built = buildCustomHealthyFood(dish as GeneratedDish, '');
      const id = registerCustomDish(built);
      out.push({ kind: 'custom', id, note, dish: dish as GeneratedDish });
    } else {
      // Catalog dish → keep only ids that exist AND belong to the requested
      // meal moment (safeguard: never show a lunch tagine for breakfast).
      const id = str(o.id);
      const food = id ? getHealthyFood(id) : null;
      if (food && (!meal || meal === 'any' || food.moments.includes(meal))) {
        out.push({ kind: 'catalog', id, note });
      }
    }
    if (out.length >= 3) break;
  }
  return out;
}

/* ── Demo-mode fallback (no Supabase / no key) ──
 * Exercises the WHOLE UI offline: meal question → preferences question →
 * understood recap → grouped dishes. */
const DEMO_TXT: Record<
  string,
  {
    ask: string;
    meals: [string, string, string];
    ask2: string;
    quick2: string[];
    recap: string;
    result: string;
  }
> = {
  fr: {
    ask: "Avec plaisir ! C'est pour quel repas ?",
    meals: ['🌅 Petit-déjeuner', '🍽️ Déjeuner', '🌙 Dîner'],
    ask2: "Des envies particulières, des allergies ou des aliments que vous n'aimez pas ?",
    quick2: ['✨ Non, surprenez-moi', '🥦 Léger', '🍗 Riche en protéines'],
    recap: "Voici ce que j'ai compris — confirmez ou modifiez avant que je génère les plats.",
    result:
      "Voici mes propositions : d'abord un plat créé spécialement pour vous, puis des plats prêts de notre sélection. Ceci reste une suggestion — validez avec votre médecin.",
  },
  ar: {
    ask: 'بفرحة! هادشي لأي وجبة؟',
    meals: ['🌅 الفطور', '🍽️ الغداء', '🌙 العشاء'],
    ask2: 'واش كتبغي شي حاجة بالخصوص، ولا عندك شي حساسية ولا ماكلة ماكتبغيهاش؟',
    quick2: ['✨ لا، فاجئني', '🥦 خفيف', '🍗 فيه البروتين'],
    recap: 'ها اللي فهمت — أكد ولا بدل قبل ما نجيب ليك الأطباق.',
    result:
      'ها الاقتراحات ديالي: طبق مصاوب ليك خصيصا، ومن بعد أطباق واجدة من اللائحة ديالنا. هادشي غير اقتراح — تأكد مع الطبيب.',
  },
  en: {
    ask: 'With pleasure! Which meal is it for?',
    meals: ['🌅 Breakfast', '🍽️ Lunch', '🌙 Dinner'],
    ask2: 'Any cravings, allergies, or foods you dislike?',
    quick2: ['✨ No, surprise me', '🥦 Light', '🍗 High protein'],
    recap: "Here's what I understood — confirm or edit before I generate the dishes.",
    result:
      'Here are my proposals: first a dish created specially for you, then ready dishes from our selection. This is only a suggestion — check with your doctor.',
  },
  de: {
    ask: 'Gerne! Für welche Mahlzeit ist es?',
    meals: ['🌅 Frühstück', '🍽️ Mittagessen', '🌙 Abendessen'],
    ask2: 'Besondere Wünsche, Allergien oder etwas, das du nicht magst?',
    quick2: ['✨ Nein, überrasch mich', '🥦 Leicht', '🍗 Proteinreich'],
    recap: 'Das habe ich verstanden — bestätige oder ändere es, bevor ich die Gerichte erstelle.',
    result:
      'Hier meine Vorschläge: zuerst ein speziell für dich erstelltes Gericht, dann fertige Gerichte aus unserer Auswahl. Nur ein Vorschlag — sprich mit deinem Arzt.',
  },
};
const ALL_ASK2 = Object.values(DEMO_TXT).map((t) => t.ask2);

/* Personalized one-liner built from the patient's LIVE data (today's
 * glucose / carbs / sport) — the coach proves it knows their day. */
const HEALTH_TXT: Record<
  string,
  {
    glucoseHigh: (v: number) => string;
    carbsHigh: (g: number) => string;
    sport: (min: number) => string;
    glucoseOk: (v: number) => string;
  }
> = {
  fr: {
    glucoseHigh: (v) => `📊 J'ai vu votre glycémie : ${v} mg/dL, au-dessus de votre cible — je vais viser des plats à IG bas.`,
    carbsHigh: (g) => `📊 Vous êtes déjà à ${g} g de glucides aujourd'hui — je vais viser des plats pauvres en glucides.`,
    sport: (m) => `💪 Bravo pour vos ${m} min de sport aujourd'hui — je prévois des protéines pour récupérer.`,
    glucoseOk: (v) => `📊 Votre dernière glycémie (${v} mg/dL) est dans la cible — on continue comme ça !`,
  },
  ar: {
    glucoseHigh: (v) => `📊 شفت السكر ديالك: ${v} mg/dL، فوق الهدف — غادي نختار ليك أطباق بمؤشر جلايسيمي منخفض.`,
    carbsHigh: (g) => `📊 راك وصلتي اليوم ${g} غرام ديال الكاربوهيدرات — غادي نختار أطباق خفيفة فالنشويات.`,
    sport: (m) => `💪 برافو على ${m} دقيقة ديال الرياضة اليوم — غادي نزيد البروتين باش ترجع القوة.`,
    glucoseOk: (v) => `📊 آخر قياس ديال السكر (${v} mg/dL) فالهدف — كمل هكا!`,
  },
  en: {
    glucoseHigh: (v) => `📊 I saw your glucose: ${v} mg/dL, above your target — I'll aim for low-GI dishes.`,
    carbsHigh: (g) => `📊 You're already at ${g} g of carbs today — I'll aim for low-carb dishes.`,
    sport: (m) => `💪 Great job on your ${m} min of activity today — I'll plan protein for recovery.`,
    glucoseOk: (v) => `📊 Your last glucose (${v} mg/dL) is in range — keep it up!`,
  },
  de: {
    glucoseHigh: (v) => `📊 Ich habe deinen Blutzucker gesehen: ${v} mg/dL, über deinem Ziel — ich wähle Gerichte mit niedrigem GI.`,
    carbsHigh: (g) => `📊 Du bist heute schon bei ${g} g Kohlenhydraten — ich wähle kohlenhydratarme Gerichte.`,
    sport: (m) => `💪 Stark, ${m} Min. Sport heute — ich plane Eiweiß zur Erholung ein.`,
    glucoseOk: (v) => `📊 Dein letzter Blutzucker (${v} mg/dL) liegt im Zielbereich — weiter so!`,
  },
};

/* Daily objective: how much of the day's reference budget (≈2000 kcal ·
 * ≈250 g carbs — same references as the detail-page rings) is left. The
 * proposals are sized to REACH that remainder, not to stay tiny under it. */
const OBJ_TXT: Record<string, (remKcal: number, remCarbs: number) => string> = {
  fr: (k, c) =>
    `📊 Il vous reste ~${k} kcal et ~${c} g de glucides sur votre objectif du jour — mes propositions sont calculées pour vous y amener.`,
  ar: (k, c) =>
    `📊 باقي ليك ~${k} kcal و ~${c} غرام ديال النشويات على هدف اليوم — الاقتراحات ديالي محسوبة باش يوصلوك للهدف.`,
  en: (k, c) =>
    `📊 You have ~${k} kcal and ~${c} g of carbs left on today's goal — my proposals are sized to take you right to it.`,
  de: (k, c) =>
    `📊 Dir bleiben heute noch ~${k} kcal und ~${c} g Kohlenhydrate bis zum Tagesziel — meine Vorschläge bringen dich genau dorthin.`,
};

/** Sensible per-meal ceiling when filling the day's remaining budget —
 *  a dinner can carry ~700 kcal, a snack shouldn't. */
const MEAL_KCAL_CAP: Record<Moment, number> = {
  ftour: 600,
  ghda: 700,
  '3cha': 700,
  snack: 300,
  drink: 150,
  dessert: 250,
};

/** One personalized sentence from the store (most important fact first). */
function demoHealthNote(language: string): string {
  const tx = HEALTH_TXT[language] ?? HEALTH_TXT.fr;
  const s = useAppStore.getState();
  const isToday = (iso: string) =>
    new Date(iso).toDateString() === new Date().toDateString();
  const glucose = s.glucoseLogs
    .filter((g) => isToday(g.created_at))
    .sort((a, b) => a.created_at.localeCompare(b.created_at));
  const last = glucose[glucose.length - 1];
  const high = s.profile?.target_high ?? 180;
  const carbs = Math.round(
    s.meals
      .filter((m) => isToday(m.created_at))
      .reduce((a, m) => a + m.result.carbohydrates, 0)
  );
  const sport = s.activityLogs
    .filter((a) => isToday(a.created_at))
    .reduce((a, x) => a + x.duration_min, 0);
  if (last && last.value > high) return tx.glucoseHigh(last.value);
  if (carbs > 150) return tx.carbsHigh(carbs);
  if (sport > 0) return tx.sport(sport);
  if (last) return tx.glucoseOk(last.value);
  return '';
}

/** Meal-time keywords across languages/dialects → the folder they map to. */
const MEAL_PATTERNS: { re: RegExp; meal: Moment }[] = [
  { re: /ft(o)?ur|petit.?d[ée]j|breakfast|fr[üu]hst[üu]ck|فطور|صباح/i, meal: 'ftour' },
  { re: /l?gh?da|d[ée]jeun|lunch|mittag|غدا|الغداء/i, meal: 'ghda' },
  { re: /l?3cha|d[îi]ner|dinner|abend|عشا|العشاء/i, meal: '3cha' },
  { re: /snack|go[ûu]ter|collation|تسناك|سناك/i, meal: 'snack' },
  { re: /dessert|nachtisch|حلو|تحلية/i, meal: 'dessert' },
  { re: /boisson|drink|getr[äa]nk|مشروب/i, meal: 'drink' },
];

/** First meal moment mentioned anywhere in the conversation (null = none). */
function detectMeal(text: string): Moment | null {
  for (const { re, meal } of MEAL_PATTERNS) if (re.test(text)) return meal;
  return null;
}

/** Localized meal label for the recap title. */
const MEAL_LABEL: Record<string, Record<Moment, string>> = {
  fr: { ftour: 'Petit-déjeuner', ghda: 'Déjeuner', '3cha': 'Dîner', snack: 'Collation', drink: 'Boisson', dessert: 'Dessert' },
  en: { ftour: 'Breakfast', ghda: 'Lunch', '3cha': 'Dinner', snack: 'Snack', drink: 'Drink', dessert: 'Dessert' },
  de: { ftour: 'Frühstück', ghda: 'Mittagessen', '3cha': 'Abendessen', snack: 'Snack', drink: 'Getränk', dessert: 'Dessert' },
  ar: { ftour: 'الفطور', ghda: 'الغداء', '3cha': 'العشاء', snack: 'تسناك', drink: 'مشروب', dessert: 'حلوى' },
};
function mealLabel(meal: Moment, lang: string): string {
  return (MEAL_LABEL[lang] ?? MEAL_LABEL.fr)[meal] ?? meal;
}

/** A message that is ONLY a meal pick (a tapped quick-reply chip). */
function isMealPick(s: string): boolean {
  const bare = s.replace(/[🌅🍽️🌙🥜🍵🍓\s]/g, '');
  return detectMeal(s) !== null && bare.length <= 14;
}
/** The generic "suggest what to eat" starters (not a concrete request). */
function isGenericAsk(s: string): boolean {
  return /propos|sugg[ée]r|schlag|essen soll|what.*eat|nakoul|nakol|اقترح|أش ناكل|شنو ناكل/i.test(s);
}
/* ── Understanding layer: the patient's requests are UNDERSTOOD and
 * rewritten cleanly — never echoed raw into the recap. ── */
const FRUITS: { re: RegExp; fr: string; en: string; de: string; ar: string }[] = [
  { re: /limou?n|citron|lemon|zitro|حامض|ليمون/i, fr: 'citron', en: 'lemon', de: 'Zitronen', ar: 'الحامض' },
  { re: /banan|موز|بنان/i, fr: 'banane', en: 'banana', de: 'Bananen', ar: 'البنان' },
  { re: /orange|letchin|برتقال|ليتشين/i, fr: 'orange', en: 'orange', de: 'Orangen', ar: 'البرتقال' },
  { re: /pomme|tefa7|apfel|apple|تفاح/i, fr: 'pomme', en: 'apple', de: 'Apfel', ar: 'التفاح' },
];
/** Fruit juices that meaningfully raise carbs/sugar for a diabetic. */
const SUGARY_FRUITS = ['banane', 'orange', 'pomme'];
const TAG_LIGHT: Record<string, string> = { fr: 'léger', en: 'light', de: 'leicht', ar: 'خفيف' };
const TAG_PROTEIN: Record<string, string> = { fr: 'riche en protéines', en: 'high protein', de: 'proteinreich', ar: 'بالبروتين' };
/** "No allergies / surprise me" answers to the preferences question. */
const NO_PREF_RE = /surpren|surprise|überrasch|فاجئ|walou|والو|^non\b|^nein\b|^no\b/i;
/** Filler tokens stripped before keeping a free-text want as-is. */
const FILLER_RE = /\b(matnsach|matnsa|tnsach|zid|zidi|liya|liyya|lia|ajoute[sz]?|ajouter|rajoute[sz]?|3tini|a3tini|bghit|aussi|auch|also|7ta|dial|dyal|chi|je veux|je voudrais|ich möchte|i want|please|stp|svp)\b/gi;
/** Meal words themselves — "bghit chi makla l lftour" is the meal request,
 *  not an extra want; nothing useful must remain of it. */
const MEAL_NOISE_RE = /\b(makla|repas|essen|food|meal|ماكلة|وجبة|l?ftour|petit.?d[ée]jeuner|breakfast|fr[üu]hst[üu]ck|فطور|l?gh?da|d[ée]jeuner|lunch|mittag(?:essen)?|غدا|الغداء|l?3cha|d[îi]ner|dinner|abend(?:essen)?|عشا|العشاء|go[ûu]ter|collation|snack|dessert|nachtisch)\b/gi;

interface ParsedWants {
  /** Clean, rephrased want tags in the app language. */
  wants: string[];
  avoid: string[];
  /** Requested drink: French label for the dish copy + localized chip label. */
  drink: { labelFr: string; label: string; sugary: boolean } | null;
  /** HARD numeric constraints the patient stated — must be obeyed exactly. */
  kcal: number | null;
  grams: number | null;
}

function parseWants(userMsgs: string[], language: string): ParsedWants {
  const lang = ['fr', 'en', 'de', 'ar'].includes(language) ? language : 'fr';
  const wants: string[] = [];
  const avoid: string[] = [];
  let drink: ParsedWants['drink'] = null;
  let kcal: number | null = null;
  let grams: number | null = null;
  for (const raw0 of userMsgs) {
    const raw = raw0.replace(/^🎙️\s*/, '').trim();
    if (!raw || isMealPick(raw) || isGenericAsk(raw) || NO_PREF_RE.test(raw)) continue;
    // Numbers the patient stated are HARD constraints ("fiha 200 calorie",
    // "plat dial 300g") — captured here, applied when the dish is built.
    const kcalM = raw.match(/(\d{2,4})\s*(?:k?cal\w*|calories?|kalorien|سعرات?|كالوري\w*)/i);
    if (kcalM) kcal = Math.min(2000, Math.max(80, parseInt(kcalM[1], 10)));
    const gramM = raw
      .replace(kcalM?.[0] ?? '', ' ')
      .match(/(\d{2,4})\s*(?:g\b|gr\b|gram\w*|غرام)/i);
    if (gramM) grams = Math.min(1500, Math.max(30, parseInt(gramM[1], 10)));
    // "bla X / sans X / ohne X" or an allergy → things to avoid.
    const av = raw.match(/(?:\bbla\b|\bsans\b|\bwithout\b|\bohne\b|بلا|بدون)\s+([^\s,.!?]+)/i);
    if (av) avoid.push(av[1]);
    // A juice/drink request → understood as "jus de <fruit>".
    if (/3q?as+ir|jus\b|juice|saft|عصير/i.test(raw)) {
      const fruit = FRUITS.find((f) => f.re.test(raw));
      if (fruit) {
        const label =
          lang === 'fr' ? `jus de ${fruit.fr}`
          : lang === 'en' ? `${fruit.en} juice`
          : lang === 'de' ? `${fruit.de}saft`
          : `عصير ${fruit.ar}`;
        drink = { labelFr: `jus de ${fruit.fr}`, label, sugary: SUGARY_FRUITS.includes(fruit.fr) };
      } else {
        drink = {
          labelFr: 'jus frais',
          label: lang === 'ar' ? 'عصير' : lang === 'de' ? 'frischer Saft' : lang === 'en' ? 'fresh juice' : 'jus frais',
          sugary: true,
        };
      }
      continue;
    }
    if (/l[ée]ger|khfif|leicht|light|خفيف/i.test(raw)) { wants.push(TAG_LIGHT[lang]); continue; }
    if (/prot[ée]in|بروتين/i.test(raw)) { wants.push(TAG_PROTEIN[lang]); continue; }
    if (av) continue; // fully consumed as an avoid
    // Unknown concrete request → keep it, minus filler verbs, meal words and
    // the numeric constraints (already captured above as kcal/grams).
    const cleaned = raw
      .replace(kcalM?.[0] ?? ' ', ' ')
      .replace(gramM?.[0] ?? ' ', ' ')
      .replace(FILLER_RE, ' ')
      .replace(MEAL_NOISE_RE, ' ')
      .replace(/\b(li|tkoun|ykoun|fiha|fih|kayn a?)\b/gi, ' ')
      .replace(/\b[ldw]\b/gi, ' ')
      .replace(/\s{2,}/g, ' ')
      .trim();
    if (cleaned.length > 2 && cleaned.length <= 60) wants.push(cleaned);
  }
  // The stated numbers become visible recap chips ("≈200 kcal").
  if (kcal) wants.push(`≈${kcal} kcal`);
  if (grams) wants.push(`≈${grams} g`);
  return {
    wants: [...new Set(wants)].slice(0, 4),
    avoid: [...new Set(avoid)].slice(0, 3),
    drink,
    kcal,
    grams,
  };
}

/** Meal-appropriate base dish for the demo custom card (French copy). */
const DEMO_BASE: Record<Moment, GeneratedDish> = {
  ftour: {
    name: 'Bol petit-déjeuner protéiné', emoji: '🥣', category: 'breakfast',
    serving: '1 bol (250 g)', grams: 250, calories: 300, carbs: 24, sugar: 8, protein: 18, fat: 13, fiber: 6, gi: 35,
    why: "Petit-déjeuner à IG bas, riche en protéines et en fibres : de l'énergie stable toute la matinée sans pic de glycémie. (Suggestion — validez avec votre médecin.)",
    ingredients: ['150 g de yaourt grec nature', "30 g de flocons d'avoine", '1 c. à s. de graines de chia', '½ pomme en dés', '5-6 amandes'],
    steps: ['Versez le yaourt dans un bol.', "Ajoutez les flocons d'avoine et la chia.", 'Ajoutez la pomme et les amandes.', 'Laissez reposer 5 min et dégustez.'],
  },
  ghda: {
    name: 'Assiette équilibrée poulet & légumes', emoji: '🍽️', category: 'main',
    serving: '1 assiette (300 g)', grams: 300, calories: 380, carbs: 30, sugar: 6, protein: 32, fat: 14, fiber: 8, gi: 40,
    why: "Protéines maigres, légumes et une petite portion de féculents complets : rassasiant et à IG modéré. (Suggestion — validez avec votre médecin.)",
    ingredients: ['130 g de poulet grillé', '4 c. à s. de quinoa cuit', 'Courgette, poivron, brocoli vapeur', "1 c. à s. d'huile d'olive", 'Citron, herbes'],
    steps: ['Grillez le poulet.', 'Faites cuire le quinoa.', 'Cuisez les légumes à la vapeur.', "Dressez et assaisonnez huile d'olive + citron."],
  },
  '3cha': {
    name: 'Soupe de légumes & œuf', emoji: '🍲', category: 'soup',
    serving: '1 bol (300 g)', grams: 300, calories: 220, carbs: 20, sugar: 7, protein: 14, fat: 9, fiber: 7, gi: 35,
    why: 'Dîner léger et chaud, riche en fibres et pauvre en glucides rapides : idéal le soir pour une glycémie stable la nuit. (Suggestion — validez avec votre médecin.)',
    ingredients: ['Légumes variés (courgette, carotte, tomate)', '1 œuf', '1 c. à s. de lentilles', "1 filet d'huile d'olive", 'Épices douces'],
    steps: ['Faites mijoter les légumes et les lentilles.', 'Mixez pour une texture lisse (facultatif).', "Ajoutez l'œuf poché.", 'Servez chaud.'],
  },
  snack: {
    name: 'En-cas protéiné anti-fringale', emoji: '🥜', category: 'snack',
    serving: '1 portion (120 g)', grams: 120, calories: 180, carbs: 12, sugar: 6, protein: 10, fat: 10, fiber: 4, gi: 30,
    why: 'Une collation à IG bas qui coupe la faim sans faire monter la glycémie. (Suggestion — validez avec votre médecin.)',
    ingredients: ['100 g de yaourt grec', '1 poignée de noix', 'Quelques fruits rouges'],
    steps: ['Mélangez le yaourt et les fruits rouges.', 'Ajoutez les noix.', 'Dégustez frais.'],
  },
  drink: {
    name: 'Boisson fraîche sans sucre', emoji: '🥤', category: 'drink',
    serving: '1 verre (250 ml)', grams: 250, calories: 40, carbs: 8, sugar: 6, protein: 1, fat: 0, fiber: 1, gi: 30,
    why: "Rafraîchissant et sans sucre ajouté : pas d'impact brutal sur la glycémie. (Suggestion — validez avec votre médecin.)",
    ingredients: ['Eau fraîche', 'Jus de citron pressé', 'Feuilles de menthe', '(option : édulcorant)'],
    steps: ['Pressez le citron.', "Mélangez avec l'eau et la menthe.", 'Servez bien frais.'],
  },
  dessert: {
    name: 'Dessert léger sans sucre', emoji: '🍓', category: 'dessert',
    serving: '1 coupe (150 g)', grams: 150, calories: 150, carbs: 16, sugar: 9, protein: 6, fat: 6, fiber: 4, gi: 35,
    why: 'Un dessert gourmand mais à IG bas et sans sucre ajouté. (Suggestion — validez avec votre médecin.)',
    ingredients: ['100 g de fromage blanc', 'Fruits rouges', '1 c. à c. de graines de chia', '(option : édulcorant)'],
    steps: ['Mélangez le fromage blanc et la chia.', 'Ajoutez les fruits rouges.', 'Réservez au frais 10 min.'],
  },
};

/** Build the demo custom dish for a meal: SCALED to the patient's stated
 *  numbers (a "200 calorie" request yields a ≈200 kcal dish, never 380),
 *  then folding in a requested drink with honest macro adjustments. */
function demoCustom(
  meal: Moment,
  drink: ParsedWants['drink'],
  kcal: number | null,
  gramsTarget: number | null
): GeneratedDish {
  let base = DEMO_BASE[meal] ?? DEMO_BASE.ghda;
  // The patient's numbers are HARD constraints → scale the whole dish.
  const f = kcal ? kcal / base.calories : gramsTarget ? gramsTarget / base.grams : 1;
  if (f !== 1) {
    const fc = Math.min(2.5, Math.max(0.25, f));
    const grams = Math.round(base.grams * fc);
    base = {
      ...base,
      grams,
      serving: /\(\d+\s*g\)/.test(base.serving)
        ? base.serving.replace(/\(\d+\s*g\)/, `(${grams} g)`)
        : `${grams} g`,
      calories: kcal ?? Math.round(base.calories * fc),
      carbs: Math.round(base.carbs * fc),
      sugar: Math.round(base.sugar * fc),
      protein: Math.round(base.protein * fc),
      fat: Math.round(base.fat * fc),
      fiber: Math.round(base.fiber * fc),
      // Gram quantities inside the ingredient lines shrink/grow too, so
      // the recipe stays coherent with the scaled serving.
      ingredients: base.ingredients.map((ing) =>
        ing.replace(/(\d+)\s*g\b/g, (_full, n) => `${Math.max(5, Math.round((parseInt(n, 10) * fc) / 5) * 5)} g`)
      ),
    };
  }
  if (!drink || meal === 'drink') return { ...base };
  const d: GeneratedDish = {
    ...base,
    name: `${base.name} + ${drink.labelFr}`,
    serving: `${base.serving} + 1 verre de ${drink.labelFr}`,
    ingredients: [...base.ingredients, `1 verre de ${drink.labelFr} frais (sans sucre ajouté)`],
    steps: [...base.steps, `Accompagnez d'un verre de ${drink.labelFr} sans sucre ajouté.`],
  };
  if (drink.sugary) {
    d.calories = base.calories + 50;
    d.carbs = base.carbs + 12;
    d.sugar = base.sugar + 10;
    d.why = `${base.why} ⚠️ Le ${drink.labelFr} est naturellement sucré : un petit verre (150 ml), de préférence pendant le repas.`;
  }
  return d;
}

/**
 * Mirror the patient (demo edition): pick the reply language from their LAST
 * message — Arabic script or Latin-Darija markers → Arabic, French/German/
 * English keywords → that language, otherwise the app language. The real AI
 * does this natively (any language, replying in Latin Darija too).
 */
function detectReplyLang(msg: string, fallback: string): string {
  const s = (msg || '').replace(/^🎙️\s*/, '');
  if (/[؀-ۿ]/.test(s)) return 'ar';
  if (/\b(bghit|wach|chno|ch7al|khass|zid|dial|dyal|liya|3andi|3endi|matnsach|nakou?l|makla|mzyan|sa7a|daba|hadchi|3assir|3afak|walou|safi)\b/i.test(s)) return 'ar';
  if (/\b(je|une?|avec|pour|manger|repas|l[ée]ger|d[ée]jeuner|d[îi]ner|envie|surprenez)\b/i.test(s)) return 'fr';
  if (/\b(ich|eine?n?|mit|f[üu]r|essen|leicht|fr[üu]hst[üu]ck|abendessen|mittagessen|m[öo]chte|[üu]berrasch)\b/i.test(s)) return 'de';
  if (/\b(i|want|with|for|eat|light|breakfast|lunch|dinner|meal|surprise)\b/i.test(s)) return 'en';
  return fallback;
}

function demoResult(
  messages: { role: 'user' | 'assistant'; content: string }[],
  language: string,
  generate: boolean
): CoachResult {
  const userMsgs = messages.filter((m) => m.role === 'user').map((m) => m.content);
  // Speak the language the patient is actually using RIGHT NOW.
  const lang = detectReplyLang(userMsgs[userMsgs.length - 1] ?? '', language);
  const tx = DEMO_TXT[lang] ?? DEMO_TXT.fr;
  const convo = userMsgs.join('\n');
  const meal = detectMeal(convo);
  const parsed = parseWants(userMsgs, lang);

  if (generate) {
    // Keep the meal chosen earlier — never drift to another one.
    const m: Moment = meal ?? 'ghda';

    // Daily objective: what's left of today's reference budget. The
    // patient's explicit calorie wish always wins; otherwise, when the
    // remaining budget is smaller than the base dish, shrink to fit it.
    const s = useAppStore.getState();
    const isToday = (iso: string) =>
      new Date(iso).toDateString() === new Date().toDateString();
    const eatenKcal = Math.round(
      s.meals.filter((x) => isToday(x.created_at)).reduce((a, x) => a + x.result.calories, 0)
    );
    const eatenCarbs = Math.round(
      s.meals.filter((x) => isToday(x.created_at)).reduce((a, x) => a + x.result.carbohydrates, 0)
    );
    const remKcal = Math.max(0, 2000 - eatenKcal);
    const remCarbs = Math.max(0, 250 - eatenCarbs);
    let kcalTarget = parsed.kcal;
    let objNote = '';
    if (!kcalTarget && eatenKcal > 0) {
      objNote = (OBJ_TXT[lang] ?? OBJ_TXT.fr)(remKcal, remCarbs);
      // Fill the remaining budget: the dish targets the WHOLE remainder
      // ("500 left" → a ≈500 kcal proposal, never a tiny 220 one), capped
      // at a sensible ceiling for this meal type.
      if (remKcal >= 120) {
        kcalTarget = Math.min(remKcal, MEAL_KCAL_CAP[m] ?? 700);
      }
    }

    const custom = demoCustom(m, parsed.drink, kcalTarget, parsed.grams);
    const cid = registerCustomDish(buildCustomHealthyFood(custom, ''));
    // AI-created dish FIRST, then ready dishes from the SAME meal folder
    // (the chat renders them as two labelled groups). With a calorie target,
    // pick the catalog dishes CLOSEST to it.
    const dishes: DishCard[] = [{ kind: 'custom', id: cid, note: '', dish: custom }];
    let cat = filterHealthyFoods('', m);
    if (kcalTarget) {
      cat = cat
        .slice()
        .sort((a, b) => Math.abs(a.calories - kcalTarget!) - Math.abs(b.calories - kcalTarget!));
    }
    for (const f of cat.slice(0, 2)) {
      dishes.push({ kind: 'catalog', id: f.id, note: '' });
    }
    return {
      reply: objNote ? `${objNote}\n\n${tx.result}` : tx.result,
      quickReplies: [],
      recap: null,
      dishes: dishes.slice(0, 3),
      transcript: '',
    };
  }

  // Guided flow: 1. learn the meal → 2. ask preferences/allergies ONCE →
  // 3. understood recap (accumulated across edits).
  if (!meal) {
    return { reply: tx.ask, quickReplies: tx.meals, recap: null, dishes: null, transcript: '' };
  }
  const askedPref = messages.some(
    (m) => m.role === 'assistant' && ALL_ASK2.some((a) => m.content.includes(a))
  );
  if (!askedPref) {
    return { reply: tx.ask2, quickReplies: tx.quick2, recap: null, dishes: null, transcript: '' };
  }

  const label = mealLabel(meal, lang);
  const withoutWord = ({ fr: 'sans', en: 'without', de: 'ohne', ar: 'بلا' } as Record<string, string>)[lang] ?? 'sans';
  // "Frühstück — leicht · Bananensaft" reads naturally in every language
  // (a "with" word clashes with adjective tags like léger/leicht).
  const wantBits = [...parsed.wants, ...(parsed.drink ? [parsed.drink.label] : [])];
  let summary = label;
  if (wantBits.length) summary += ` — ${wantBits.join(' · ')}`;
  if (parsed.avoid.length) summary += ` · ${withoutWord} ${parsed.avoid.join(', ')}`;
  // The coach proves it knows the patient's day (glucose / carbs / sport).
  const note = demoHealthNote(lang);
  return {
    reply: note ? `${note}\n\n${tx.recap}` : tx.recap,
    quickReplies: [],
    recap: { title: label, meal, summary, wants: wantBits.slice(0, 4), avoid: parsed.avoid },
    dishes: null,
    transcript: '',
  };
}

/**
 * Ask the healthy-meal coach. Normal turns gather info / return a recap;
 * pass `generate: true` (the "Générer" button) to get the dish cards.
 * Personalized with the patient's health snapshot and the curated catalog.
 */
export async function healthyCoach(
  messages: { role: 'user' | 'assistant'; content: string }[],
  language: string,
  profile: Profile | null,
  opts: {
    generate?: boolean;
    audio?: { mimeType: string; data: string };
    /** The meal moment the recap settled on — dishes are filtered to it. */
    meal?: Moment | 'any' | null;
  } = {}
): Promise<CoachResult> {
  const generate = !!opts.generate;

  if (isDemoMode || !supabase) {
    await new Promise((r) => setTimeout(r, generate ? 900 : 600));
    return demoResult(messages, language, generate);
  }

  // On "Générer", end the conversation on a clear user intent so Gemini
  // produces the dishes for this turn (the `generate` flag drives the mode).
  const turns = generate
    ? [...messages, { role: 'user' as const, content: 'Génère maintenant les plats.' }]
    : messages;

  const { data, error } = await supabase.functions.invoke('ai-chat', {
    body: {
      messages: turns,
      language,
      profile,
      mode: 'healthy_coach',
      generate,
      meal: opts.meal ?? null,
      healthData: buildHealthContext(),
      // Full chronological journal (today + yesterday: every meal with its
      // details, every dose, every measure, sport) — same depth the insulin
      // engine gets, so the coach truly knows the patient's day.
      dayJournal: buildAIDayJournal(),
      catalog: healthyFoodAIIndex(),
      ...(opts.audio ? { audio: opts.audio } : {}),
    },
  });
  const quota = await asQuotaError(error, data);
  if (quota) throw quota;
  if (error) throw error;
  if (data?.error) throw new Error(data.error);

  const r = (data?.result ?? {}) as Record<string, unknown>;
  return {
    reply: str(r.reply),
    quickReplies: strArr(r.quickReplies).slice(0, 4),
    recap: parseRecap(r.recap),
    dishes: parseDishes(r.dishes, opts.meal),
    transcript: str(r.transcript),
  };
}
