/** DISH-SPECIFIC real photos (Wikimedia Commons, ~1600px) for the world
 * dishes catalog. Generated by scripts/fetch-world-dish-images.mjs.
 * Missing dishes fall back to a gradient card + an AI-resolved photo on
 * the detail screen. */
export const WORLD_DISH_IMAGES: Record<string, { thumb: string }> = {
  "baghrir": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/6/66/Baghrir_patisserie_algerienne.jpg"
  },
  "harcha": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Harcha_%28Homemade%29.jpg/1920px-Harcha_%28Homemade%29.jpg"
  },
  "batbout": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Batbout.jpg/1920px-Batbout.jpg"
  },
  "khobz-zit": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Amal_Women%27s_Training_Center_and_Moroccan_Restaurant_trainee_making_bread.jpg/1920px-Amal_Women%27s_Training_Center_and_Moroccan_Restaurant_trainee_making_bread.jpg"
  },
  "bissara-ma": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Bissara_%28Moroccan_Dip%29.JPG/1920px-Bissara_%28Moroccan_Dip%29.JPG"
  },
  "couscous": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/c/c7/Couscous_osbanes_de_sardines.jpg"
  },
  "couscous-poulet": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Couscous_with_Chicken_and_Vegetable_Stew.JPG/1920px-Couscous_with_Chicken_and_Vegetable_Stew.JPG"
  },
  "couscous-boeuf": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/c/c7/Couscous_osbanes_de_sardines.jpg"
  },
  "tajine-poulet": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Moroccan_food-Chicken_tagine_with_preserved_lemons_and_olives-01.jpg/1920px-Moroccan_food-Chicken_tagine_with_preserved_lemons_and_olives-01.jpg"
  },
  "tajine-boeuf-pruneaux": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/9/95/Tagine_d%27agneau.jpg"
  },
  "tajine-legumes": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Chermoula_tagine.jpg/1920px-Chermoula_tagine.jpg"
  },
  "rfissa": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/6/6a/Rfissa.JPG"
  },
  "pastilla": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/5/51/Pastilla_au_poulet.jpg"
  },
  "harira": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/6/62/Harira_oranaise.png"
  },
  "loubia": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Loubia.jpg/1920px-Loubia.jpg"
  },
  "adass": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Moroccan_cuisine-Lentil_soup-01.jpg/1920px-Moroccan_cuisine-Lentil_soup-01.jpg"
  },
  "brochettes-kefta": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/1/16/Moroccan_made_kefta_from_Tetouan_%28675_x_506%29.jpg"
  },
  "brochettes-poulet": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Korean_spicy_chicken_skewers_%286325410086%29.jpg/1920px-Korean_spicy_chicken_skewers_%286325410086%29.jpg"
  },
  "mechoui": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/9/96/Mechoui.jpg"
  },
  "tanjia": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Tanjia_gold_discs%2C_Shaanxi_History_Museum.jpg/1920px-Tanjia_gold_discs%2C_Shaanxi_History_Museum.jpg"
  },
  "seffa": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/1/12/Seffa_blahlib_ou_Semoule_de_bl%C3%A9_cuit_%C3%A0_la_vapeur.jpg"
  },
  "batbout-farci": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Batbout.jpg/1920px-Batbout.jpg"
  },
  "karan": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/1/1b/Karan_Brar_%2850091153148%29.jpg"
  },
  "maakouda": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Maakouda.jpg/1920px-Maakouda.jpg"
  },
  "salade-marocaine": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Moroccan_salad-02.jpg/1920px-Moroccan_salad-02.jpg"
  },
  "zaalouk": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Zaalouk-01.JPG/1920px-Zaalouk-01.JPG"
  },
  "chebakia": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Chebakia.jpg/1920px-Chebakia.jpg"
  },
  "sellou": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Sellou.JPG/1920px-Sellou.JPG"
  },
  "kaab-ghzal": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/1/11/Kaab_El_Ghazal_the_famous_traditional_moroccan_cookies.jpg"
  },
  "ghriba": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Synagogue_de_la_Ghriba_Djerba_11.jpg/1920px-Synagogue_de_la_Ghriba_Djerba_11.jpg"
  },
  "briouat-amande": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/4/45/Briouat_-_Kefta.jpg"
  },
  "pizza": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg"
  },
  "pates-bolognaise": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/8/83/Spaghetti_Bolognese.jpg"
  },
  "lasagnes": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Lasagne_in_Germany.jpg/1920px-Lasagne_in_Germany.jpg"
  },
  "burger": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/NCI_Visuals_Food_Hamburger.jpg/1920px-NCI_Visuals_Food_Hamburger.jpg"
  },
  "panini": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Panini_1.jpg/1920px-Panini_1.jpg"
  },
  "tacos-marocain": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Smoked_chicken_and_avocado_wrap.jpg/1920px-Smoked_chicken_and_avocado_wrap.jpg"
  },
  "shawarma": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/b/b7/Shawarma_closeup.png"
  },
  "omelette": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Bread_Omelette_5.jpg/1920px-Bread_Omelette_5.jpg"
  },
  "salade-cesar": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Caesar_salad_%282%29.jpg/1920px-Caesar_salad_%282%29.jpg"
  },
  "ratatouille": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/2/27/Ratatouille.jpg"
  },
  "poulet-roti": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Roasted_chicken_leg_piece-MB20.jpg/1920px-Roasted_chicken_leg_piece-MB20.jpg"
  },
  "quiche-lorraine": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Bywater_Bakery_Quiche_New_Orleans_April_2018.jpg/1920px-Bywater_Bakery_Quiche_New_Orleans_April_2018.jpg"
  },
  "soupe-oignon": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/c/c9/Mmm...onion_soup_%285344349906%29.jpg"
  },
  "nicoise": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Salade_nicoise.jpg/1920px-Salade_nicoise.jpg"
  },
  "boeuf-bourguignon": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/6/6b/Cookbook-beef-stew.jpg"
  },
  "risotto": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Risotto_de_gambas%2C_restaurant_Danieli_%28Vienne%2C_Autriche%29.jpg/1920px-Risotto_de_gambas%2C_restaurant_Danieli_%28Vienne%2C_Autriche%29.jpg"
  },
  "minestrone": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Minestrone_soup.jpg/1920px-Minestrone_soup.jpg"
  },
  "caprese": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Caprese-1.jpg/1920px-Caprese-1.jpg"
  },
  "paella": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/e/ed/01_Paella_Valenciana_original.jpg"
  },
  "tortilla": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Tortilla_paname%C3%B1a.jpg/1920px-Tortilla_paname%C3%B1a.jpg"
  },
  "gazpacho": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Gazpacho_Cazuela_Barro.jpg/1920px-Gazpacho_Cazuela_Barro.jpg"
  },
  "lentil-soup-tr": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Lentil_soup_done.jpg/1920px-Lentil_soup_done.jpg"
  },
  "kofte": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/7/7e/EgFoodKofta.jpg"
  },
  "tabbouleh": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flickr_-_cyclonebill_-_Tabbouleh.jpg/1920px-Flickr_-_cyclonebill_-_Tabbouleh.jpg"
  },
  "hummus": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Hummus_from_The_Nile.jpg/1920px-Hummus_from_The_Nile.jpg"
  },
  "falafel": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Falafel_1.JPG/1920px-Falafel_1.JPG"
  },
  "koshari": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Eggplant_Turnovers%2C_Tomato_Rice%2C_Lentils_and_Saffron_Rice_at_Moroccan_Soup_Bar.jpg/1920px-Eggplant_Turnovers%2C_Tomato_Rice%2C_Lentils_and_Saffron_Rice_at_Moroccan_Soup_Bar.jpg"
  },
  "foul-medames": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Fava_beans_at_the_Sonoma_Farmer%27s_Market_-_Sarah_Stierch.jpg/1920px-Fava_beans_at_the_Sonoma_Farmer%27s_Market_-_Sarah_Stierch.jpg"
  },
  "greek-salad": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/5/5f/Greek_Salad_Choriatiki.jpg"
  },
  "souvlaki": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Souvlaki_in_Athens.JPG/1920px-Souvlaki_in_Athens.JPG"
  },
  "dal": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/a/a6/Paolo_dal_Pozzo_Toscanelli_1.jpg"
  },
  "chicken-curry": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Chicken_Curry_4.jpg/1920px-Chicken_Curry_4.jpg"
  },
  "biryani": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/3/38/Dum_Biryani_Plate.jpg"
  },
  "stir-fry": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Stir_fry_%C3%A0_la_Gabi-showcasingbabycorn.jpg/1920px-Stir_fry_%C3%A0_la_Gabi-showcasingbabycorn.jpg"
  },
  "pad-thai": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Phat_Thai_kung_Chang_Khien_street_stall.jpg/1920px-Phat_Thai_kung_Chang_Khien_street_stall.jpg"
  },
  "sushi": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Various_sushi%2C_beautiful_October_night_at_midnight.jpg/1920px-Various_sushi%2C_beautiful_October_night_at_midnight.jpg"
  },
  "ramen": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Ramen_Jump_002.jpg/1920px-Ramen_Jump_002.jpg"
  },
  "tacos-mexicain": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/001_Tacos_de_carnitas%2C_carne_asada_y_al_pastor.jpg/1920px-001_Tacos_de_carnitas%2C_carne_asada_y_al_pastor.jpg"
  },
  "guacamole": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Guacamole_IMGP1256.jpg/1920px-Guacamole_IMGP1256.jpg"
  },
  "bratwurst": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/8/8e/Russian_Sausage_Making.jpg"
  },
  "kartoffelsalat": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Potato_salad_001.jpg/1920px-Potato_salad_001.jpg"
  },
  "schnitzel": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/a/ae/Wiener-Schnitzel02.jpg"
  },
  "grilled-salmon": {
    "thumb": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Pink_salmon_FWS.jpg/1920px-Pink_salmon_FWS.jpg"
  }
};
